# NYT and Transcription Analysis

In [29]:
import os
import pandas as pd

In [30]:
# get combined pdf to access dates

cwd = os.getcwd()
metadata_dir = f'{cwd}/../pre-processing/metadata-csv'
metadata_files = [file for file in os.listdir(metadata_dir) if "Sec2Gr3_" in file]      # only get metadata files for our group

dataframes = []

for file in metadata_files:
    file_path = os.path.join(metadata_dir, file)
    df = pd.read_csv(file_path)
    dataframes.append(df)

combined_df = pd.concat(dataframes, ignore_index=True)

In [31]:
combined_df.head()

,video_id,video_timestamp,video_duration,video_locationcreated,suggested_words,video_diggcount,video_sharecount,video_commentcount,video_playcount,video_description,video_is_ad,video_stickers,author_username,author_name,author_followercount,author_followingcount,author_heartcount,author_videocount,author_diggcount,author_verified
0,7273221955937914155,2023-08-30T16:56:01,37.0,US,"angels in tibet, angels in tibet dance, angels...",356300.0,5606.0,986.0,2000000.0,Replying to @jade🐉not perfect yet & i made a ...,False,NaN,thebeaulexx,beaulexx,NaN,NaN,NaN,NaN,NaN,False
1,7273221955937914155,2023-08-30T16:56:01,37.0,US,"angels in tibet, angels in tibet dance, angels...",356300.0,5606.0,986.0,2000000.0,Replying to @jade🐉not perfect yet & i made a ...,False,NaN,thebeaulexx,beaulexx,NaN,NaN,NaN,NaN,NaN,False
2,7283080657893379334,2023-09-26T06:32:40,15.0,PH,"angels in tibet, Jam Republic, angels in tibet...",419100.0,3518.0,708.0,2600000.0,🧠🧠🧠,False,NaN,clarkie_cpm,Clarkie,NaN,NaN,NaN,NaN,NaN,False
3,7273221955937914155,2023-08-30T16:56:01,37.0,US,"angels in tibet, angels in tibet dance, angels...",356300.0,5606.0,986.0,2000000.0,Replying to @jade🐉not perfect yet & i made a ...,False,NaN,thebeaulexx,beaulexx,NaN,NaN,NaN,NaN,NaN,False
4,7285397643725983008,2023-10-02T12:23:48,37.0,US,"Dream Academy, angels in tibet, Adela Dream Ac...",142700.0,1373.0,551.0,1000000.0,s/o to dream academy for teaching me how to da...,False,NaN,adelajergova,ADÉLA,NaN,NaN,NaN,NaN,NaN,False

In [32]:
transcript_dir = f'{cwd}/../transcription /txt-transcripts/'

transcripts = [file for file in os.listdir(transcript_dir) if file.endswith('.txt')]

transcript_dict = {'video_id': [], 'transcription': []}

for file in transcripts:
    video_id = file.split('.')[0]
    with open(os.path.join(transcript_dir, file), "r") as transcription_file:
        transcription = transcription_file.read()

    transcript_dict['video_id'].append(video_id)
    transcript_dict['transcription'].append(transcription)

transcript_df = pd.DataFrame(transcript_dict)

In [33]:
transcript_df

                video_id                                      transcription
0    7236076693822246170                                              Outro
1    7295142634719415595                      Yeah, yeah, uh, hang up. Huh?
2    7305273374962371882   Here's Curry. Curry looking to take Wembley. ...
3    7299203592739704106   We have an awesome bathtub. It's a jacuzzi tu...
4    7295523111103991083   Lalalilililililililililililililililililililil...
..                   ...                                                ...
264  7088395289219976490   Should people continue to wear masks on plane...
265  6866180645400431877   Do you have supervision? I'm going to give yo...
266  7282735903003381010                                              Music
267  7300191041280412933                      Nothing's new, nothing's new.
268  7231173879845113131   One of the biggest questions I always get ask...

[269 rows x 2 columns]

In [41]:
transcript_df.to_csv('transcripts.csv')

In [34]:
date_df = combined_df[['video_id', 'video_timestamp']]
date_df['video_date'] = date_df['video_timestamp'].str[:10]

/var/folders/ny/5mz_1h8j5c31x__pd0t4xhxw0000gn/T/ipykernel_7369/3389850981.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  date_df['video_date'] = date_df['video_timestamp'].str[:10]

In [35]:
date_df['video_date'].unique()

array(['2023-08-30', '2023-09-26', '2023-10-02', '2023-05-09',
       '2023-05-22', '2023-10-04', '2023-09-09', '2023-12-05',
       '2023-12-03', '2023-12-01', '2023-10-28', '2023-11-21',
       '2023-12-04', '2023-10-20', '2023-11-30', '2023-11-17',
       '2023-12-06', '2023-11-20', '2023-11-23', '2023-11-22',
       '2023-10-14', '2023-10-23', '2023-12-02', '2023-11-27',
       '2023-10-27', '2023-11-14', '2023-11-26', '2023-09-28',
       '2023-11-29', '2023-11-24', '2023-03-23', '2022-07-03',
       '2023-06-21', '2023-08-05', '2023-03-12', '2022-07-16',
       '2023-11-16', '2023-11-15', '2023-11-03', '2023-07-15',
       '2022-09-24', '2022-10-08', '2023-11-06', '2023-11-19',
       '2023-11-18', '2023-11-13', '2023-09-25', '2023-11-08',
       '2020-12-02', '2022-12-28', '2022-12-09', '2023-10-15',
       '2022-11-19', '2023-11-11', '2023-11-04', '2023-10-19',
       '2023-06-09', '2023-04-06', '2023-03-14', '2023-10-30',
       '2023-11-05', '1969-12-31', '2022-06-16', '2023-10-06',
       '2023-09-14', '2023-11-28', '2023-11-01', '2022-08-28',
       '2023-07-26', '2023-05-02', '2021-05-09', '2023-03-27',
       '2023-07-25', '2023-10-18', '2023-11-25', '2023-07-16',
       '2023-09-11', '2023-11-02', '2023-11-07', '2023-10-29',
       '2023-06-27', '2023-11-12', '2022-12-06', '2023-09-08',
       '2022-12-03', '2023-10-21', '2023-11-09', '2023-10-13',
       '2023-10-26', '2023-10-11', '2023-10-12', '2021-02-03',
       '2021-07-23', '2023-11-10', '2023-09-21', '2023-09-27',
       '2023-09-19', '2023-09-10', '2023-10-25', '2023-04-16',
       '2022-12-24', '2023-09-18', '2022-07-23', '2022-12-16',
       '2023-01-21', '2023-03-02', '2023-09-01', '2023-08-24',
       '2023-09-02', '2023-06-19', '2022-02-07', '2023-04-10',
       '2023-08-08', '2023-02-01', '2023-10-09', '2023-07-02',
       '2023-06-04', '2023-08-25', '2023-06-25', '2023-09-16',
       '2023-10-03', '2023-01-14', '2023-06-22', '2022-05-13',
       '2021-04-19', '2023-02-02', '2021-08-31', '2023-10-05',
       '2023-08-15', '2023-10-16', '2023-06-13', '2023-04-25',
       '2023-02-24', '2023-04-22', '2023-03-09', '2022-01-24',
       '2023-04-05', '2023-07-27', '2022-11-03', '2022-01-23',
       '2021-02-15', '2023-03-30', '2023-04-03', '2023-04-04',
       '2023-08-28', '2022-07-12', '2022-06-21', '2022-06-20',
       '2022-06-13', '2022-06-06', '2022-06-23', '2022-12-27',
       '2022-06-22', '2022-11-17', '2022-12-14', '2023-03-24',
       '2022-05-26', '2021-11-12', '2023-10-31', '2022-11-23',
       '2023-08-12', '2021-04-06', '2023-02-23', '2023-10-22',
       '2023-06-28', '2022-07-07', '2023-01-13', '2023-01-27',
       '2023-04-21', '2023-05-03', '2023-05-14', '2023-05-30',
       '2023-06-12', '2023-08-16', '2023-08-21', '2023-08-31',
       '2023-01-30', '2022-09-22', '2021-03-17', '2021-02-09',
       '2022-08-05', '2021-12-20', '2022-08-02', '2023-05-27',
       '2021-02-17', '2023-04-17', '2023-09-05', '2021-11-24',
       '2021-08-09', '2023-03-11', '2023-03-13', '2023-03-15',
       '2023-03-16', '2023-03-17', '2023-03-18', '2023-03-19',
       '2023-04-29', '2023-05-23', '2023-06-14', '2023-06-30',
       '2023-07-03', '2023-07-10', '2023-07-11', '2023-07-12',
       '2023-07-13', '2023-07-14', '2023-08-27', '2023-04-08',
       '2023-03-21', '2023-08-20', '2023-05-10', '2023-08-06',
       '2023-05-20', '2023-07-06', '2023-03-22', '2023-07-22',
       '2023-05-06', '2022-11-30', '2023-05-11', '2023-10-08',
       '2022-06-11', '2023-06-01', '2022-11-10', '2021-01-16',
       '2022-12-05', '2022-11-21', '2022-07-19', '2023-02-28',
       '2023-08-01', '2023-01-26', '2023-01-23', '2023-07-29',
       '2022-04-30', '2023-02-08', '2023-10-10', '2023-03-03',
       '2023-04-02', '2023-02-10', '2022-12-30', '2023-02-09',
       '2023-01-24', '2023-02-15', '2023-03-07', '2023-02-05',
       '2023-02-11', '2023-03-31', '2023-02-17', '2023-03-04',
       '2023-02-13', '2023-08-09', '2023-08-22', '2023-02-20',
       '2022-10-02', '2023-05-16', '2021-05-19', '2022-08-30',
       '2023-04-27', '2022-05-20', '2021-06-22', '2023-04-09',
       '2019-03-01', '2020-10-25', '2022-12-01', '2023-05-01',
       '2023-04-30', '2022-03-31', '2022-12-11', '2023-09-17',
       '2022-10-27', '2021-08-26', '2022-09-14', '2023-09-30',
       '2023-06-15', '2023-07-20', '2022-11-05', '2023-03-06',
       '2023-09-12', '2022-11-29', '2021-02-08', '2023-05-07',
       '2022-12-21', '2023-06-07', '2023-10-17', '2021-12-04',
       '2023-07-04', '2023-07-19', '2022-10-14', '2022-08-13',
       '2022-10-03', '2021-11-09', '2022-10-28', '2022-10-30',
       '2022-04-13', '2022-11-22', '2023-09-24', '2022-05-04',
       '2020-08-25', '2023-07-01', '2023-06-10', '2021-08-21',
       '2023-04-23', '2021-07-07', '2021-11-21', '2022-10-24',
       '2023-05-31', '2023-09-13', '2023-09-22', '2021-11-01',
       '2023-04-13', '2023-09-29', '2021-01-01', '2023-10-07',
       '2022-04-25', '2023-02-04', '2023-01-10', '2023-03-28',
       '2022-01-11', '2023-06-03', '2023-02-12', '2022-08-24',
       '2023-02-03', '2023-08-04', '2023-02-21', '2023-07-23',
       '2023-03-10', '2023-05-25', '2023-09-23', '2023-09-15',
       '2023-10-01', '2023-10-24', '2022-10-11', '2023-05-08',
       '2021-04-18', '2022-03-06', '2022-12-22', '2023-01-29',
       '2021-02-23', '2023-01-09', '2023-04-19', '2023-02-18',
       '2023-01-01', '2022-12-15', '2019-12-08', '2022-10-25',
       '2022-02-19', '2019-11-26', '2023-06-24', '2022-12-29',
       '2023-08-13', '2022-04-02', '2022-11-08', '2021-08-30',
       '2023-06-20', '2023-08-10', '2022-08-27', '2022-12-18',
       '2022-02-08', '2023-06-16', '2022-12-31', '2023-05-15',
       '2020-05-06', '2022-05-27', '2023-04-07', '2022-08-21',
       '2023-06-08', '2023-02-14', '2023-08-02', '2021-03-06',
       '2023-02-26', '2023-06-02', '2023-05-17', '2021-12-16',
       '2022-05-21', '2023-01-06', '2023-09-06', '2020-08-28',
       '2022-06-15', '2021-09-01', '2022-09-18', '2023-01-20',
       '2022-03-25', '2023-02-27', '2023-01-19', '2022-02-14',
       '2022-05-08', '2021-09-05', '2023-08-26', '2022-04-19',
       '2023-08-23', '2023-08-18', '2023-08-11', '2023-08-14',
       '2023-06-23', '2023-06-26', '2023-08-17', '2023-05-04',
       '2021-12-12', '2022-06-25', '2023-08-29', '2023-03-25',
       '2022-01-18', '2022-04-27', '2022-10-22', '2022-11-18',
       '2023-03-20', '2022-07-26', '2023-07-17', '2021-07-17',
       '2021-07-22', '2022-01-16', '2022-04-10', '2020-05-22',
       '2021-10-21', '2022-12-26', '2023-02-25', '2022-01-10',
       '2022-01-19', '2021-08-13', '2023-05-13', '2023-01-11',
       '2021-04-01', '2023-04-15', '2021-02-26', '2021-10-11',
       '2021-05-13', '2021-05-11', '2023-02-22', '2023-04-20',
       '2021-01-10', '2023-04-12', '2022-10-01', '2023-03-29',
       '2022-05-16', '2022-10-26', '2021-04-27', '2023-01-04',
       '2022-10-19', '2023-09-04', '2023-06-05', '2021-08-15',
       '2022-02-02', '2020-01-15', '2022-08-31', '2020-11-17',
       '2021-05-28', '2022-09-06', '2022-07-15', '2021-09-02',
       '2021-12-31', '2023-09-07', '2021-08-29', '2023-02-06',
       '2023-01-02', '2022-05-01', '2022-12-07', '2022-12-19',
       '2021-12-01', '2022-08-20', '2021-10-28', '2022-09-17',
       '2022-10-12', '2021-09-25', '2023-02-07', '2022-03-02',
       '2023-04-11', '2022-11-12', '2023-01-22', '2022-06-09',
       '2023-06-18', '2020-06-04', '2023-04-14', '2021-12-06',
       '2023-07-09', '2022-08-15', '2023-09-20', '2022-05-02',
       '2021-03-09', '2022-04-01', '2022-09-07', '2022-11-13',
       '2021-02-10', '2021-09-14', '2023-07-28', '2022-07-17',
       '2023-07-24', '2022-09-05', '2023-02-19', '2021-10-10',
       '2022-09-16', '2020-08-29', '2021-04-08', '2021-06-12',
       '2020-07-12', '2022-10-31', '2022-11-09', '2021-05-31',
       '2023-01-15', '2021-08-18', '2022-12-23', '2021-06-20',
       '2022-02-22', '2023-09-03', '2021-01-08', '2022-08-12',
       '2022-08-26', '2022-01-03', '2021-06-05', '2023-05-29',
       '2021-06-23', '2022-02-28', '2020-02-22', '2020-03-30',
       '2021-06-09', '2021-10-16', '2021-10-18', '2021-10-23',
       '2022-04-07', '2022-07-21', '2022-08-09', '2022-08-25',
       '2022-11-25', '2023-01-08', '2021-10-22', '2021-06-24',
       '2022-06-01', '2023-05-05', '2022-04-15', '2022-12-20',
       '2022-04-06', '2023-08-07', '2021-10-29', '2022-11-02',
       '2023-08-03', '2023-04-18', '2021-11-03', '2022-04-05',
       '2023-04-28', '2023-01-05', '2022-07-14', '2020-10-11',
       '2022-04-17', '2023-05-19', '2022-04-18', '2022-07-28',
       '2021-07-10', '2021-07-06', '2021-04-25', '2023-05-18',
       '2022-02-25', '2022-07-11', '2022-10-29', '2022-03-27',
       '2020-12-10', '2022-03-19', '2021-02-18', '2022-05-09',
       '2022-05-03', '2021-09-12', '2021-08-24', '2022-05-31',
       '2023-05-28', '2020-12-31', '2020-12-29', '2023-01-25',
       '2022-05-19', '2022-05-07', '2022-05-15', '2020-08-15',
       '2022-11-04', '2023-05-26', '2022-02-17', '2021-08-16',
       '2022-04-11', '2021-04-29', '2022-09-01', '2021-04-28',
       '2022-06-30', '2020-11-26', '2022-09-11', '2021-05-27',
       '2022-09-15', '2022-01-22', '2021-06-26', '2022-09-28',
       '2021-10-30', '2023-03-01', '2021-02-16', '2023-06-11',
       '2023-01-18', '2022-01-31', '2022-09-09', '2022-08-07',
       '2022-08-23', '2022-11-27', '2023-01-07', '2021-02-12',
       '2022-06-24', '2023-06-29', '2018-10-10', '2021-08-25',
       '2023-05-24', '2023-08-19', '2022-09-29', '2020-03-17',
       '2023-07-05', '2021-09-07', '2021-03-30', '2022-01-20',
       '2023-03-05', '2022-06-05', '2022-02-26', '2022-10-10',
       '2021-10-20', '2022-12-13', '2022-06-07', '2022-10-16',
       '2022-10-18', '2022-08-01', '2023-07-07', '2022-10-21',
       '2023-04-26', '2022-01-17', '2022-03-26', '2022-05-25',
       '2023-07-31', '2022-05-22', '2022-08-18', '2021-12-09',
       '2022-07-13', '2023-07-18', '2021-07-25', '2022-09-26',
       '2022-11-11', '2022-05-28', '2021-12-21', '2022-06-12',
       '2022-07-04', '2022-12-12', '2023-01-16', '2021-09-28',
       '2020-03-28', '2023-07-08', '2022-08-10', '2022-08-22',
       '2021-03-11', '2021-11-23', '2021-12-22', '2022-09-03',
       '2020-09-30', '2022-05-12', '2023-07-30', '2021-02-14',
       '2021-01-27', '2022-01-30', '2022-03-07', '2022-05-11',
       '2022-04-20', '2021-11-27', '2021-11-22', '2022-10-09',
       '2021-06-30', '2022-07-27', '2021-09-08', '2023-05-21',
       '2022-12-02', '2021-12-29', '2022-03-16', '2023-06-17',
       '2023-04-24', '2021-06-16', '2021-01-21', '2022-09-08',
       '2021-12-28', '2021-10-24', '2020-09-12', '2022-02-15',
       '2021-03-18', '2022-03-18', '2022-12-08', '2021-05-01',
       '2020-12-04', '2022-01-14', '2022-09-30', '2021-10-31',
       '2020-09-13', '2022-11-01', '2022-10-15', '2021-10-26',
       '2021-09-29', '2022-09-23', '2020-11-01', '2023-01-12',
       '2021-05-17', '2021-03-08', '2022-03-05', '2021-10-05',
       '2021-12-05', '2021-06-19', '2021-12-14', '2022-02-06',
       '2021-02-28', '2023-07-21', '2020-07-05', '2022-08-17',
       '2022-07-09', '2023-06-06', '2022-07-05', '2021-09-03',
       '2019-10-14', '2021-03-24', '2022-06-29', '2022-09-27',
       '2021-10-02', '2022-07-30', '2021-09-26', '2021-04-21',
       '2021-05-22', '2023-01-28', '2023-03-26', '2022-04-26',
       '2022-05-05', '2022-11-20', '2021-07-14', '2022-10-13',
       '2022-06-08', '2020-08-21', '2021-10-17', '2021-08-19',
       '2020-10-18', '2020-03-04', '2022-11-14', '2021-01-04',
       '2022-02-13', '2021-02-24', '2020-07-02', '2021-01-06',
       '2022-07-01', '2023-01-31', '2023-05-12', '2022-10-06',
       '2022-06-04', '2020-04-20', '2021-11-13', '2020-10-26',
       '2022-09-02', '2021-05-12', '2021-11-17', '2021-05-14',
       '2020-11-09', '2020-07-24', '2021-10-04', '2021-06-25',
       '2021-08-04', '2021-11-29', '2022-06-10', '2022-07-10',
       '2021-05-06', '2021-07-08', '2022-03-03', '2023-02-16',
       '2022-11-28', '2022-11-06', '2021-06-07', '2021-06-17',
       '2022-04-21', '2022-09-25', '2021-10-07', '2023-04-01',
       '2020-11-12', '2021-03-21', '2021-09-06', '2022-04-16',
       '2023-01-03', '2022-08-16', '2021-01-14', '2021-11-20',
       '2020-07-15', '2021-04-30', '2021-11-18', '2020-09-23',
       '2021-07-27', '2021-08-03', '2022-03-12', '2020-10-24',
       '2021-05-07', '2021-03-31', '2020-10-31', '2022-03-17',
       '2021-02-19', '2021-11-07', '2022-02-04', '2021-07-01',
       '2021-06-29', '2023-01-17', '2022-03-04', '2020-05-05',
       '2022-01-02', '2021-05-25', '2022-11-24', '2021-11-10',
       '2021-07-13', '2021-05-24', '2021-11-28', '2021-03-16',
       '2021-08-23', '2022-03-20', '2022-07-24', '2021-08-01',
       '2022-07-18', '2021-04-02', '2022-10-23', '2022-10-17',
       '2022-10-04', '2021-10-14', '2021-10-12', '2020-10-20',
       '2022-05-14', '2022-09-12', '2021-02-01', '2022-11-15',
       '2022-09-19', '2023-03-08', '2022-06-27', '2022-11-26',
       '2022-04-08', '2021-09-20', '2022-09-20', '2022-12-25',
       '2022-04-22', '2021-02-25', '2022-06-17', '2021-08-08',
       '2022-06-19', '2021-12-26', '2022-05-30', '2022-12-17',
       '2022-07-29', '2021-11-25', '2022-05-17', '2021-01-18',
       '2022-11-16', '2020-11-28', '2020-09-09', '2022-01-12',
       '2022-04-03', '2022-10-20', '2020-09-11', '2021-06-11',
       '2021-05-18', '2021-06-28', '2021-03-03', '2021-08-28',
       '2021-02-13', '2020-06-17', '2022-09-04', '2020-12-03',
       '2022-05-24', '2021-10-01', '2022-06-28', '2020-03-27',
       '2021-12-15', '2021-04-11', '2021-05-03'], dtype=object)

In [36]:
transcript_id_list = transcript_df['video_id'].to_list()
video_id_list = date_df['video_id'].to_list()

In [40]:
intersection = list(set(transcript_id_list).intersection(set(video_id_list)))
intersection

[]

In [38]:
date_df_2 = date_df[date_df['video_id'].isin(video_id_list)]
date_df_2

                  video_id      video_timestamp  video_date
0      7273221955937914155  2023-08-30T16:56:01  2023-08-30
1      7273221955937914155  2023-08-30T16:56:01  2023-08-30
2      7283080657893379334  2023-09-26T06:32:40  2023-09-26
3      7273221955937914155  2023-08-30T16:56:01  2023-08-30
4      7285397643725983008  2023-10-02T12:23:48  2023-10-02
...                    ...                  ...         ...
24910  7283846172425407750  2023-09-28T08:03:16  2023-09-28
24911  7285527057394584863  2023-10-02T20:46:05  2023-10-02
24912  7284024264334806315  2023-09-28T19:34:23  2023-09-28
24913  7284462467290303787  2023-09-29T23:55:02  2023-09-29
24914  7286843613030518059  2023-10-06T09:55:17  2023-10-06

[24915 rows x 3 columns]

In [39]:
date_df['video_id'].isin(video_id_list).unique()

array([ True])